### PR TITLE
EVA-993 - Update Documentation and add CircleCI to quartermaster

### PR DESCRIPTION
**Pull request by tylerwilding-wk**
Add some public facing documentation for each of our libraries / services.

Also we need CircleCI to automate releases.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by erikpetersen-wf** [comment]
+10

**Comment by erikpetersen-wf** [comment]
@Workiva/release-management-pp

**Comment by tylerwilding-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
