### PR TITLE
EVA-883 Initial Commit to opensource repository

### PR DESCRIPTION
**Pull request by tylerwilding-wk**

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by alexalegre-wf** [comment]
LGTM

**Comment by teresarevious-wf** [comment]
RM +1 dependencies verified on initial release https://github.com/Workiva/quartermaster/pull/4

**Comment by teresarevious-wf** [comment]
infosec review will be accounted for in assessment

**Pull request merged**
